language:
  - C

compiler:
  - clang
  - gcc

script:
  - export BEEP_DEBUG_BUILD=yes
  - make -j 2 DESTDIR="$PWD/_i"
  - env BEEP_LOG_LEVEL=999 ./beep || true
  - make -j 2 DESTDIR="$PWD/_i" install
  - ./beep --version > beep-usage.from--version
  # - grep "$(date +%Y)" beep-usage.from--version
  - cat beep-usage.from--version
  - ./beep --help > beep-usage.from--help
  - diff -u beep-usage.txt beep-usage.from--help
  - ls -l
  - ls -lR _i/

matrix:
  include:
    - os: linux
      dist: bionic
      arch: amd64
    - os: linux
      dist: bionic
      arch: arm64
    - os: linux
      dist: bionic
      arch: ppc64le
    - os: linux
      dist: xenial
      arch: amd64
    - os: linux
      dist: xenial
      arch: arm64
    - os: linux
      dist: xenial
      arch: ppc64le
    - os: linux
      dist: trusty
      arch: amd64
    - os: linux
      dist: trusty
      arch: arm64
    - os: linux
      dist: trusty
      arch: ppc64le
